### ISSUE TITLE
If downloadTo location is set, tools are not cached

### ISSUE THREAD

**Issue by dziedrius** [JetBrains/profiler-self-api#3]
If I'm ensuring prerequisites like this:
```
DotTrace.EnsurePrerequisite(downloadTo: @"C:\temp\dottrace");
```
next time application is ran, it will again download tools.
I guess the problem is, that it actually will extract downloaded package to C:\temp\dottrace\dotTrace\2021.3.2 and code still tries to find dotTrace.exe under given downloadTo path, in other words - C:\temp\dottrace\dotTrace.exe

**Comment by gassanosh** [comment]
Self api is expected to be used with specific clt version. So when self api downloads clt it places it to folder with version suffix. Also if self api finds proper version in such folders it won't download it again. However self api can download newer version of clt (for example if bugfix or security fix for clt is released). But anyway the self api won't download the same version of clt twice.
However some environments don't have access to the Internet. For such case you can disable downloading placing clt right into download folder. If the clt will be found here the self api will use it even if it's not compatible. So if you want to use this feature make sure you use proper clt.
So, in your case if you put clt to `C:\temp\dottrace\dotTrace.exe` - the version checking and downloading will be disabled.
But if you manually create `2021.3.2` folder and put clt inside (which in fact is not expected to be done by self api user) self api will check if `2021.3.2` is a desired version and otherwise will download a proper version.
